declare const MD_DOMAIN: string
declare const MD_RECENT_UPDATES: string
declare const MD_MANGA_API: string
declare const MD_CHAPTER_API: string
declare const MD_USER_FOLLOWS: string
declare const MD_USER_FOLLOWS_OLD: string
declare const MD_USER: string
declare const MD_HOMEPAGE_SETTINGS: string
declare const MD_LOGOUT: string
declare const MD_LIST_UPDATE: string
declare const MD_LIST_UNFOLLOW: string
declare const MD_CHAPTER_READ: string
declare const MD_CHAPTER_UNREAD: string
declare const MD_TITLES: string
declare const CACHE_DOMAIN: string
declare const CACHE_IMAGE_RESOLVER: string
declare const CACHE_SEARCH: string
declare const CACHE_MANGA: string
declare const CACHE_TAGS: string
declare const CACHE_PING: string
declare const CACHE_AUTH: string
declare const USER_AGENT: string
declare const APP_VERSION: string
declare const IS_PUBLIC: string
