import './Chapter/Chapter_impl'
import './ChapterDetails/ChapterDetails_impl'
import './HomeSection/HomeSection_impl'
import './Manga/Manga_impl'
import './MangaTile/MangaTile_impl'
import './RequestObject/RequestObject_impl'
import './SearchRequest/SearchRequest_impl'
import './TagSection/TagSection_impl'